import { IconSymbolName } from "@/components/ui/icon-symbol";


const selectableIcons : IconSymbolName[] = [
  "figure.walk",
  "bicycle",
  "book.fill",
  "music.note",
  "fork.knife",
  "cart.fill",
  "gamecontroller.fill",
  "paintpalette.fill",
  "briefcase.fill",
  "leaf.fill",
  "film.fill",
  "graduationcap.fill",
  "calendar",
  "sparkles",
  "cloud.sun.fill",
  "house.fill",
  "star.fill",
  "moon.fill",
  "sun.max.fill",
  "heart.fill",
  "flag.fill",
  "map.fill",
  "tshirt.fill",
  "bag.fill",
  "music.mic",
  "theatermasks.fill",
  "basketball.fill",
  "flame.fill",
  "airplane",
  "tent.fill",
  "pawprint.fill",
  "books.vertical.fill",
  "person.2.fill",
  "person.3.fill",
  "megaphone.fill",
  "mappin.and.ellipse",
  "gift.fill",
  "party.popper.fill",
  "wineglass.fill",
  "cup.and.saucer.fill",
  "music.note.list",
  "guitars.fill",
  "paintbrush.pointed.fill",
  "camera.fill",
  "figure.run",
  "soccerball",
  "globe.europe.africa.fill",
];

export default selectableIcons;