spring.datasource.url=jdbc:h2:mem:meetup
spring.datasource.username=admin
spring.datasource.password=admin
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

jwt.secret=f289fdadd521f0b84334d08ebf0dbcba52a822f61008f1c46c01b26a615f8351
jwt.expiration=28800000