spring.datasource.url=jdbc:postgresql://localhost:5432/meetup
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

# Optional SQL initialization
spring.sql.init.mode=never

server.port=3030